name: Deploy

on:
  push:
    branches:
      - development

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          appdir: ./frontend
          branch: development
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "skinncarehub" #Must be unique in Heroku
          heroku_email: "rmikrathnayaka@students.nsbm.ac.lk"
  backend:
    needs: [frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          appdir: ./backend
          branch: development
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "skinncarehub" #Must be unique in Heroku
          heroku_email: "rmikrathnayaka@students.nsbm.ac.lk"
